[telegram]
token = "8996267827:AAFr90VroINCcdtYPWX3ZWJ2m2vq3LxY-ao"
workers = 1
admins = [8294554523]
admins_only = false
maintenance_mode = false
persistent_temp_data = true

[pyrogram]
enabled = false
api_id = 0
api_hash = ""

[sqlite]
filename = "stickersbot.sqlite"

[bot]
sourcecode = ""
issues = ""
channel = ""
